### ISSUE TITLE
Rank the MpegTsInputTransformer ahead of the VideoInputTransformer (from DDF)

### ISSUE THREAD

**Issue by brjeter** [codice/alliance#734]
This is so that, if the MpegTsInputTransformer is installed, mpeg files are run through that transformer first instead of the [VideoInputTransformer from DDF](https://github.com/codice/ddf/blob/master/catalog/transformer/catalog-transformer-video-input/src/main/java/ddf/catalog/transformer/input/video/VideoInputTransformer.java).

**Comment by shaundmorris** [comment]
Marking as resolved by the PR metioned in the issue.
